solve arrays
lazycoder9/study pull request #1
Opened 2018-12-29 20:29 UTC by lazycoder9

2019-01-14 20:56 UTC, Andrew8xx8 requested changes

2019-01-14 20:56 UTC, Andrew8xx8 commented on test/exercise/arrays/solution.rb
> +        array.map { |x| x.negative? ? x : array.max }
Это хорошо, что ты воспользовалься стандартной функцией, так нужно делать всегда, но в рамках этого задания следует реализовать метод `max` самому.

2019-01-14 20:56 UTC, Andrew8xx8 commented on test/exercise/arrays/solution.rb
> +        iter = lambda do |left, right|
Оправдано ли здесь использование лямбды? Можно переписать без создания новой функции?

2019-01-14 21:02 UTC, lazycoder9 commented on test/exercise/arrays/solution.rb
> +        iter = lambda do |left, right|
Не люблю циклы, предпочитаю рекурсию) наверное хотел посмотреть, каково оно, программировать функционально на руби) но переделать не вопрос, через while

2019-01-14 21:15 UTC, Andrew8xx8 commented on test/exercise/arrays/solution.rb
> +        iter = lambda do |left, right|
Для этого есть следующее задание, а в этом создание дополнительных функций внутри функции ни к чему

2019-01-19 16:37 UTC, lazycoder9 commented
@Andrew8xx8 зарефакторил

2019-01-21 08:11 UTC, Andrew8xx8 approved these changes

2019-01-21 11:15 UTC, merged